spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes[0]:
        id: service-customer
        uri: lb://SERVICE-CUSTOMER
        predicates[0]: Path=/api/v1/customers/**,/api/v1/customerTypes/**
      routes[1]:
        id: service-customer-product
        uri: lb://SERVICE-CUSTOMER-PRODUCT
        predicates[0]: Path=/api/v1/customerProductsPassive/**,/api/v1/customerProductsActive/**
      routes[2]:
        id: service-operation
        uri: lb://SERVICE-OPERATION
        predicates[0]: Path=/api/v1/operations/**,/api/v1/operationTypes/**
      routes[3]:
        id: service-payment
        uri: lb://SERVICE-PAYMENT
        predicates[0]: Path=/api/v1/payment/**
      routes[4]:
        id: service-product
        uri: lb://SERVICE-PRODUCT
        predicates[0]: Path=/api/v1/products/**,/api/v1/productTypes/**
      routes[5]:
        id: service-shopping
        uri: lb://SERVICE-PRODUCT
        predicates[0]: Path=/api/v1/shoppings/**
    loadbalancer:
      ribbon:
        enabled: false
server:
  port: 8000